name: Windows CI

on: 
    workflow_dispatch:

jobs:
    build:
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          include:
            - os: ubuntu-latest
              arch: amd64
              build: buildLinux
            - os: ubuntu-latest
              arch: arm64
              build: buildLinux
            - os: macos-latest
              arch: amd64
              build: buildIOS
            - os: macos-latest
              arch: arm64
              build: buildIOS
            - os: windows-latest
              arch: amd64
              build: buildWindows
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Setup Go environment
          uses: actions/setup-go@v5
          with:
            go-version: '1.22'
  
        - name: Check Go version
          run: go version
  
        - name: Compile Go program for ${{ matrix.os }} ${{ matrix.arch }}
          run: |
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              export GOOS=windows
            elif [ "${{ matrix.os }}" = "macos-latest" ]; then
              export GOOS=darwin
            else
              export GOOS=linux
            fi
            export GOARCH=${{ matrix.arch }}
            if [ "${{ matrix.os }}" = "windows-latest" ]; then
              ./bootstrap_install_mage.bat
            else
              chmod +x ./bootstrap_install_mage.sh
              echo "$HOME/go/bin:$PATH" >> $GITHUB_PATH
              ./bootstrap_install_mage.sh
            fi
            mage ${{ matrix.build }}
  
        - name: Upload Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: ${{ matrix.os }}-${{ matrix.arch }}-assets
            path: shared/${{ (matrix.os == 'macos-latest' && 'ios' || (matrix.os == 'windows-latest' && 'windows' || 'linux')) }}/
  